import os
import logging
import warnings
warnings.filterwarnings("ignore")
logging.getLogger("chromadb").setLevel(logging.ERROR)

from groq import Groq
from fpdf import FPDF
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

GROQ_MODEL   = os.getenv("GROQ_MODEL",   "llama-3.3-70b-versatile")
OUTPUT_PATH  = os.getenv("OUTPUT_PATH",  "./outputs")
groq_client  = Groq(api_key=os.getenv("GROQ_API_KEY"))

os.makedirs(OUTPUT_PATH, exist_ok=True)


def _generate_checklist_items(school_name, level, state, extra_context=""):
    """
    Use Groq LLM with CoT prompting to generate a
    personalized application checklist for a school.
    """
    cot_prompt = f"""
You are EduNavigator AI, an expert college and school admissions consultant.

Generate a detailed application checklist for:
School : {school_name}
Level  : {level}
State  : {state}
Context: {extra_context if extra_context else "Standard application"}

Using Chain-of-Thought reasoning:
1. CONSIDER the education level and typical requirements
2. IDENTIFY standard documents needed for this level
3. ADD level-specific requirements (SAT for universities, immunizations for preschool etc.)
4. INCLUDE timeline and deadlines advice
5. ADD scholarship and financial aid items if applicable

Return ONLY a JSON object in exactly this format, no other text:
{{
  "checklist": {{
    "Academic Documents": [
      "Item 1",
      "Item 2"
    ],
    "Personal Documents": [
      "Item 1",
      "Item 2"
    ],
    "Application Requirements": [
      "Item 1",
      "Item 2"
    ],
    "Financial Documents": [
      "Item 1",
      "Item 2"
    ],
    "Important Deadlines": [
      "Item 1",
      "Item 2"
    ]
  }},
  "tips": [
    "Tip 1",
    "Tip 2",
    "Tip 3"
  ]
}}
"""
    response = groq_client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an admissions expert. "
                    "Return only valid JSON, no markdown, "
                    "no explanation, no code blocks."
                )
            },
            {
                "role": "user",
                "content": cot_prompt
            }
        ],
        max_tokens=800,
        temperature=0.1
    )
    return response.choices[0].message.content


def _build_pdf(school_name, level, state, checklist_data, tips):
    """Build and save the PDF checklist file."""

    class EduPDF(FPDF):
        def header(self):
            self.set_fill_color(30, 58, 95)
            self.rect(0, 0, 210, 28, "F")
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(255, 255, 255)
            self.set_xy(0, 8)
            self.cell(0, 12, "EduNavigator AI - Application Checklist", align="C")
            self.set_text_color(0, 0, 0)
            self.ln(24)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(150, 150, 150)
            self.cell(
                0, 10,
                f"Generated by EduNavigator AI  |  "
                f"{datetime.now().strftime('%B %d, %Y')}  |  "
                f"Page {self.page_no()}",
                align="C"
            )

    pdf = EduPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── School Info Block ──────────────────────────
    pdf.set_fill_color(227, 242, 253)
    pdf.rect(10, 30, 190, 22, "F")
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 58, 95)
    pdf.set_xy(14, 33)
    pdf.cell(0, 7, f"School: {school_name}", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.set_x(14)
    pdf.cell(
        0, 6,
        f"Level: {level}   |   State: {state}   |   "
        f"Generated: {datetime.now().strftime('%B %d, %Y')}",
        ln=True
    )
    pdf.ln(10)

    # ── Checklist Sections ─────────────────────────
    section_colors = {
        "Academic Documents":       (232, 245, 233),
        "Personal Documents":       (243, 229, 245),
        "Application Requirements": (227, 242, 253),
        "Financial Documents":      (255, 248, 225),
        "Important Deadlines":      (252, 228, 236),
    }

    for section, items in checklist_data.items():
        if not items:
            continue

        # Section header
        r, g, b = section_colors.get(section, (240, 240, 240))
        pdf.set_fill_color(r, g, b)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 58, 95)
        pdf.set_x(10)
        pdf.cell(190, 8, f"  {section}", fill=True, ln=True)
        pdf.ln(2)

        # Checklist items with checkboxes
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for item in items:
            pdf.set_x(14)
            pdf.cell(8,  7, "[ ]")
            pdf.cell(172, 7, item, ln=True)
        pdf.ln(4)

    # ── Tips Section ───────────────────────────────
    if tips:
        pdf.set_fill_color(30, 58, 95)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(255, 255, 255)
        pdf.set_x(10)
        pdf.cell(190, 8, "  Pro Tips from EduNavigator AI", fill=True, ln=True)
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for i, tip in enumerate(tips, 1):
            pdf.set_x(14)
            pdf.multi_cell(182, 6, f"{i}. {tip}")
            pdf.ln(1)

    # ── Save PDF ───────────────────────────────────
    safe_name = school_name.replace(" ", "_").replace("/", "-")
    filename  = f"{safe_name}_checklist.pdf"
    filepath  = os.path.join(OUTPUT_PATH, filename)
    pdf.output(filepath)
    return filepath


def doc_specialist_agent(school_name, level, state, extra_context=""):
    """
    Document Specialist Agent — generates a personalized
    PDF application checklist for a given school.

    Returns:
        dict with keys:
            - filepath     : path to the generated PDF
            - checklist    : dict of checklist sections
            - tips         : list of pro tips
            - school_name  : name of the school
    """
    print(f"\n📄 Doc Specialist Agent activated for: '{school_name}'")

    # ── Step 1: Generate checklist via LLM ────────
    print("   🤖 Generating personalized checklist...")
    try:
        raw_response = _generate_checklist_items(
            school_name, level, state, extra_context
        )

        # Clean response and parse JSON
        import json
        clean = raw_response.strip()
        if clean.startswith("```"):
            clean = clean.split("```")[1]
            if clean.startswith("json"):
                clean = clean[4:]
        clean = clean.strip()

        parsed      = json.loads(clean)
        checklist   = parsed.get("checklist", {})
        tips        = parsed.get("tips", [])
        print(f"   ✅ Checklist generated with {sum(len(v) for v in checklist.values())} items.")

    except Exception as e:
        print(f"   ❌ LLM/parse error: {e}")
        # Fallback checklist
        checklist = {
            "Academic Documents":       ["Official transcripts", "Test scores (SAT/ACT if applicable)"],
            "Personal Documents":       ["Government-issued ID", "Proof of residency"],
            "Application Requirements": ["Completed application form", "Personal statement or essay"],
            "Financial Documents":      ["Financial aid forms (FAFSA if applicable)", "Proof of income"],
            "Important Deadlines":      ["Check school website for current deadlines"]
        }
        tips = [
            "Start your application at least 3 months before the deadline.",
            "Keep copies of all submitted documents.",
            "Follow up with the admissions office after submission."
        ]

    # ── Step 2: Build PDF ──────────────────────────
    print("   📝 Building PDF checklist...")
    try:
        filepath = _build_pdf(school_name, level, state, checklist, tips)
        print(f"   ✅ PDF saved to: {filepath}")
    except Exception as e:
        print(f"   ❌ PDF error: {e}")
        filepath = None

    return {
        "filepath":    filepath,
        "checklist":   checklist,
        "tips":        tips,
        "school_name": school_name
    }